### ISSUE TITLE
the script can't read some files

### ISSUE THREAD

**Issue by hananelroe** [geoffrey45/swingmusic#101]
here's the error:

`[11:35:02]@swing • Could not read file: /home/hananelroe/anaconda3/envs/3dRenderer/lib/python3.1/site-packages/scipy/io/tests/data/test-8000Hz-be-3ch-5S-24bit.wav`

`[11:35:02]@swing • Could not read file: /home/hananelroe/anaconda3/lib/python3.9/site-packages/scipy/io/tests/data/test-8000Hz-be-3ch-5S-24bit.wav`

`[11:35:02]@swing • Could not read file: /home/hananelroe/Desktop/phone backup/Music/רכבת לילה לקהיר.mp3`

`[11:35:02]@swing • Could not read file: /home/hananelroe/anaconda3/lib/python3.9/site-packages/scipy/io/tests/data/test-44100Hz-be-1ch-4bytes.wav`

`[11:35:02]@swing • Could not read file: /home/hananelroe/Desktop/phone backup/Music/כמה הייתי רוצה.mp3`

I thought that some of it might be because the filenames are in hebrew, but it managed to read most of the hebrew files.

**Comment by geoffrey45** [comment]
The files are most probably broken and their metatags can't be read. You won't see these audio files in the app.

**Comment by hananelroe** [comment]
but I know they aren't broken because other apps are able to play them...

**Comment by geoffrey45** [comment]
That's interesting. I'll investigate with some of my files and see what's going on.

**Comment by hananelroe** [comment]
if you'd like i could send you the faulty file(s)

**Comment by geoffrey45** [comment]
That would be nice. Send them over. Thanks

**Comment by geoffrey45** [comment]
We'll check them out. Thanks
